#!/usr/bin/env node
import { program } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';
import * as path from 'path';
import { initCommand } from './commands/init';
import { videoCommand } from './commands/video';
import { configCommand } from './commands/config';
import { renderCommand } from './commands/render';
import { VideoFormat } from '../shared/types';

const pkg = require('../../package.json');

console.log(chalk.bold.hex('#6C63FF')('\n🎬 RepoReel') + chalk.gray(` v${pkg.version}\n`));

program
  .name('reporeel')
  .description('Turn any repo into a promotional video — in one command.')
  .version(pkg.version);

program
  .command('init')
  .description('Scan your repo and create a RepoReel context file')
  .option('--path <path>', 'Path to repo (default: current directory)', '.')
  .action(initCommand);

program
  .command('config')
  .description('Set API keys and preferences')
  .argument('<action>', 'set | get | list')
  .argument('[keyvalue]', 'KEY=value pair for set action')
  .action(configCommand);

program
  .command('render')
  .description('Agent-Native Mode: Render a video from a JSON script generated by your AI agent')
  .argument('<scriptPath>', 'Path to the script.json file')
  .action((scriptPath) => renderCommand(scriptPath));

// Dynamically load video commands from the 'skills' directory!
const skillsDir = path.join(process.cwd(), 'skills');
if (fs.existsSync(skillsDir)) {
  const skillFiles = fs.readdirSync(skillsDir).filter(f => f.endsWith('.md'));
  
  for (const file of skillFiles) {
    const commandName = file.replace('.md', '');
    
    program
      .command(commandName)
      .description(`Generate a ${commandName} video from this repository`)
      .option('--output <path>', 'Output file path', `reproreel-${commandName}.mp4`)
      .option('--dry-run', 'Show script and cost estimate only, do not generate')
      .action((options) => {
        // Execute the video generation with this specific skill/format
        videoCommand({
          type: commandName as VideoFormat,
          output: options.output,
          aiVideo: true,
          resolution: '720p',
          dryRun: options.dryRun || false
        });
      });
  }
}

program.parse(process.argv);
